### ISSUE TITLE
Build error (SyntaxError: invalid syntax: post.isFixedPitch = 0L)

### ISSUE THREAD

**Issue by kidonng** [Pal3love/Source-Han-TrueType#7]
Source Han Sans released [2.001](https://github.com/adobe-fonts/source-han-sans/releases/tag/2.001) version a month ago, before waiting for this repo to update I'd like to build myself.
At first I used Travis CI (on Ubuntu Trusty with Python 3.7) to build the fonts but failed ([Full log](https://api.travis-ci.com/v3/job/201382936/log.txt), please skip the archive download process and scroll to the end), then I built on my Windows 10 (18362.113) with Python 3.7.3, but encountered the same error: [(Full log)](https://github.com/Pal3love/Source-Han-TrueType/files/3196420/error.log)

```
Traceback (most recent call last):
  File "C:\Users\kidonng\scoop\apps\python\current\Scripts\otrebuild-script.py", line 11, in <module>
    load_entry_point('otrebuilder==1.5.6', 'console_scripts', 'otrebuild')()
  File "c:\users\kidonng\scoop\apps\python\3.7.3\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\kidonng\scoop\apps\python\3.7.3\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "c:\users\kidonng\scoop\apps\python\3.7.3\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "c:\users\kidonng\scoop\apps\python\3.7.3\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\kidonng\scoop\apps\python\3.7.3\lib\site-packages\otRebuilder\otrebuild.py", line 19, in <module>
    from otRebuilder.Lib import Initializer
  File "c:\users\kidonng\scoop\apps\python\3.7.3\lib\site-packages\otRebuilder\Lib\Initializer.py", line 270
    post.isFixedPitch = 0L
                         ^
SyntaxError: invalid syntax
```

I'm not familiar with Python, could you please help me fix the error or kindly update the fonts to 2.001? Many thanks!

**Comment by RollingSnack** [comment]
You could modify the problematic python file. Just discard the letter 'L' like ```post.isFixedPitch = 0``` and try to run it again.

In python 3, there is only one integer type, int, which is represented as a long integer. Long for python 2 is no longer available in 3.
I guess this project is still built on python 2 and does not support 3. You may encounter other problems.

**Comment by kidonng** [comment]
@RollingSnack Thanks for the tip! There is already a PR about Python 3 on otRebuilder: Pal3love/otRebuilder#4
And someone else has built Source Han Sans 2.001 in TrueType format already (https://github.com/be5invis/source-han-sans-ttf), so I'm not going to bother with this anymore.

**Comment by Pal3love** [comment]
Thanks a lot for the concerns regarding my previous otRebuilder repo! I understand that it's super out-of-date and must be refactored. I'll start rewriting in Python 3 and FontTools 4.29+ soon. For now please simply use the native builds under Script directory in this repo.
